In [2]:
import pandas as pd
import numpy as np

In [3]:
aisles = pd.read_csv('aisles.csv')
departments = pd.read_csv('departments.csv')
orders = pd.read_csv('orders.csv')
products = pd.read_csv('products.csv')
order_products__train = pd.read_csv('order_products__train.csv')
order_products__prior = pd.read_csv('order_products__prior.csv')

In [5]:
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [24]:
aisles['aisle'].unique()

array(['prepared soups salads', 'specialty cheeses',
       'energy granola bars', 'instant foods',
       'marinades meat preparation', 'other', 'packaged meat',
       'bakery desserts', 'pasta sauce', 'kitchen supplies',
       'cold flu allergy', 'fresh pasta', 'prepared meals',
       'tofu meat alternatives', 'packaged seafood', 'fresh herbs',
       'baking ingredients', 'bulk dried fruits vegetables',
       'oils vinegars', 'oral hygiene', 'packaged cheese', 'hair care',
       'popcorn jerky', 'fresh fruits', 'soap', 'coffee', 'beers coolers',
       'red wines', 'honeys syrups nectars', 'latino foods',
       'refrigerated', 'packaged produce', 'kosher foods',
       'frozen meat seafood', 'poultry counter', 'butter',
       'ice cream ice', 'frozen meals', 'seafood counter',
       'dog food care', 'cat food care', 'frozen vegan vegetarian',
       'buns rolls', 'eye ear care', 'candy chocolate', 'mint gum',
       'vitamins supplements', 'breakfast bars pastries',
       'packaged poultry', 'fruit vegetable snacks',
       'preserved dips spreads', 'frozen breakfast', 'cream',
       'paper goods', 'shave needs', 'diapers wipes', 'granola',
       'frozen breads doughs', 'canned meals beans', 'trash bags liners',
       'cookies cakes', 'white wines', 'grains rice dried goods',
       'energy sports drinks', 'protein meal replacements', 'asian foods',
       'fresh dips tapenades', 'bulk grains rice dried goods',
       'soup broth bouillon', 'digestion',
       'refrigerated pudding desserts', 'condiments', 'facial care',
       'dish detergents', 'laundry', 'indian foods', 'soft drinks',
       'crackers', 'frozen pizza', 'deodorants',
       'canned jarred vegetables', 'baby accessories', 'fresh vegetables',
       'milk', 'food storage', 'eggs', 'more household', 'spreads',
       'salad dressing toppings', 'cocoa drink mixes', 'soy lactosefree',
       'baby food formula', 'breakfast bakery', 'tea',
       'canned meat seafood', 'lunch meat', 'baking supplies decor',
       'juice nectars', 'canned fruit applesauce', 'missing',
       'air fresheners candles', 'baby bath body care',
       'ice cream toppings', 'spices seasonings',
       'doughs gelatins bake mixes', 'hot dogs bacon sausage',
       'chips pretzels', 'other creams cheeses', 'skin care',
       'pickled goods olives', 'plates bowls cups flatware', 'bread',
       'frozen juice', 'cleaning products',
       'water seltzer sparkling water', 'frozen produce',
       'nuts seeds dried fruit', 'first aid', 'frozen dessert', 'yogurt',
       'cereal', 'meat counter', 'packaged vegetables fruits', 'spirits',
       'trail mix snack mix', 'feminine care', 'body lotions soap',
       'tortillas flat bread', 'frozen appetizers sides',
       'hot cereal pancake mixes', 'dry pasta', 'beauty',
       'muscles joints pain relief', 'specialty wines champagnes'],
      dtype=object)

In [6]:
departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [26]:
departments['department'].unique()

array(['frozen', 'other', 'bakery', 'produce', 'alcohol', 'international',
       'beverages', 'pets', 'dry goods pasta', 'bulk', 'personal care',
       'meat seafood', 'pantry', 'breakfast', 'canned goods',
       'dairy eggs', 'household', 'babies', 'snacks', 'deli', 'missing'],
      dtype=object)

In [12]:
orders.head(20)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0
11,2168274,2,prior,1,2,11,NaN
12,1501582,2,prior,2,5,10,10.0
13,1901567,2,prior,3,1,10,3.0
14,738281,2,prior,4,2,10,8.0
15,1673511,2,prior,5,3,11,8.0
16,1199898,2,prior,6,2,9,13.0
17,3194192,2,prior,7,2,12,14.0
18,788338,2,prior,8,1,15,27.0
19,1718559,2,prior,9,2,9,8.0

In [14]:
orders.shape

(3421083, 7)

In [13]:
orders['order_id'].nunique()

3421083

In [27]:
orders['eval_set'].unique()

array(['prior', 'train', 'test'], dtype=object)

In [16]:
orders['eval_set'].unique()

array(['prior', 'train', 'test'], dtype=object)

In [6]:
orders['days_since_prior_order'].isna().sum()

np.int64(206209)

In [8]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [19]:
products['aisle_id'].isna().sum()

np.int64(0)

In [20]:
products['department_id'].isna().sum()

np.int64(0)

In [21]:
products['product_name'].unique()

array(['Chocolate Sandwich Cookies', 'All-Seasons Salt',
       'Robust Golden Unsweetened Oolong Tea', ..., 'Artisan Baguette',
       'Smartblend Healthy Metabolism Dry Cat Food',
       'Fresh Foaming Cleanser'], shape=(49688,), dtype=object)

In [22]:
products['product_name'].value_counts()

product_name
Chocolate Sandwich Cookies                         1
Black Raspberry Water                              1
Organic Egg Whites                                 1
Oikos Yogurt Drink, Strawberry                     1
Peanut Butter Dark Chocolate Protein Chewy Bars    1
                                                  ..
Fajita Mix                                         1
Premium Enriched Egg Noodles Barley Shape          1
Dishwasher Detergent                               1
Hummus Original                                    1
Fresh Foaming Cleanser                             1
Name: count, Length: 49688, dtype: int64

In [23]:
products.shape

(49688, 4)

In [15]:
order_products__train.head(20)

    order_id  product_id  add_to_cart_order  reordered
0          1       49302                  1          1
1          1       11109                  2          1
2          1       10246                  3          0
3          1       49683                  4          0
4          1       43633                  5          1
5          1       13176                  6          0
6          1       47209                  7          0
7          1       22035                  8          1
8         36       39612                  1          0
9         36       19660                  2          1
10        36       49235                  3          0
11        36       43086                  4          1
12        36       46620                  5          1
13        36       34497                  6          1
14        36       48679                  7          1
15        36       46979                  8          1
16        38       11913                  1          0
17        38       18159                  2          0
18        38        4461                  3          0
19        38       21616                  4          1

In [11]:
order_products__prior.head(20)

    order_id  product_id  add_to_cart_order  reordered
0          2       33120                  1          1
1          2       28985                  2          1
2          2        9327                  3          0
3          2       45918                  4          1
4          2       30035                  5          0
5          2       17794                  6          1
6          2       40141                  7          1
7          2        1819                  8          1
8          2       43668                  9          0
9          3       33754                  1          1
10         3       24838                  2          1
11         3       17704                  3          1
12         3       21903                  4          1
13         3       17668                  5          1
14         3       46667                  6          1
15         3       17461                  7          1
16         3       32665                  8          1
17         4       46842                  1          0
18         4       26434                  2          1
19         4       39758                  3          1

In [28]:
order_products__train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           1384617 non-null  int64
 1   product_id         1384617 non-null  int64
 2   add_to_cart_order  1384617 non-null  int64
 3   reordered          1384617 non-null  int64
dtypes: int64(4)
memory usage: 42.3 MB

In [29]:
order_products__prior.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  int64
 3   reordered          int64
dtypes: int64(4)
memory usage: 989.8 MB